//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBlade.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources__Windows_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources__Windows_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZBlade.Properties.Resources [Windows]", typeof(Resources__Windows_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] bgBottom {
            get {
                object obj = ResourceManager.GetObject("bgBottom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bladeBorder {
            get {
                object obj = ResourceManager.GetObject("bladeBorder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bladeGloss {
            get {
                object obj = ResourceManager.GetObject("bladeGloss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] key1 {
            get {
                object obj = ResourceManager.GetObject("key1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] key2 {
            get {
                object obj = ResourceManager.GetObject("key2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] key6 {
            get {
                object obj = ResourceManager.GetObject("key6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] menuArrow {
            get {
                object obj = ResourceManager.GetObject("menuArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] menuchoice {
            get {
                object obj = ResourceManager.GetObject("menuchoice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] menuhighlight {
            get {
                object obj = ResourceManager.GetObject("menuhighlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] progressbarOverlay {
            get {
                object obj = ResourceManager.GetObject("progressbarOverlay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Segoe_UI_10 {
            get {
                object obj = ResourceManager.GetObject("Segoe_UI_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Segoe_UI_12 {
            get {
                object obj = ResourceManager.GetObject("Segoe_UI_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Segoe_UI_14 {
            get {
                object obj = ResourceManager.GetObject("Segoe_UI_14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] textbox {
            get {
                object obj = ResourceManager.GetObject("textbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
